FROM postgres:16.9-alpine
RUN apk add --no-cache --update \
    build-base \
    clang19 \
    llvm19 \
    git \
    postgresql-dev \
    && rm -rf /var/cache/apk/*
WORKDIR /tmp
RUN git clone https://github.com/pgvector/pgvector.git
WORKDIR /tmp/pgvector
RUN make
RUN make install
