#!/usr/bin/env python

import logging
import os

_logger = logging.getLogger(__name__)


RESOURCES = os.environ.get("RESOURCES")
SOURCES = os.environ.get("SOURCES")
EXTRA_ADDONS = os.path.join(SOURCES, "extra-addons")

addons = [
    os.path.join(SOURCES, "community", "addons"),
    os.path.join(SOURCES, "community", "odoo", "addons"),
]

# Handle enterprise
if os.path.isdir(os.path.join(SOURCES, "enterprise")):
    addons.insert(0, os.path.join(SOURCES, "enterprise"))

# Image repositories, usually dependencies
extra_addons = []
if os.path.isdir(EXTRA_ADDONS):
    extra_addons = [
        os.path.join(EXTRA_ADDONS, d)
        for d in sorted(os.listdir(EXTRA_ADDONS))
        if os.path.isdir(os.path.join(EXTRA_ADDONS, d))
    ]

# Repo addons are preprended, in case we want to overwrite odoo modules
addons = extra_addons + addons

# Overwrite 10-addons.conf
msg = f"Updating addons_path.. {addons}"
_logger.debug(msg)
with open(
    os.path.join(RESOURCES, "conf.d", "10-addons.conf"), "w+", encoding="utf-8"
) as file:
    file.write("[options]\naddons_path = %s" % ",".join(addons))
