#!/usr/bin/env bash
set -e

# First, we need to get the directory of this script.
# See: https://stackoverflow.com/a/246128
SRC=${BASH_SOURCE[0]}
while [ -L "$SRC" ]; do # resolve $SRC until the file is no longer a symlink
    DIR=$( cd -P "$( dirname "$SRC" )" >/dev/null 2>&1 && pwd )
    SRC=$(readlink "$SRC")
    [[ $SRC != /* ]] && SRC=$DIR/$SRC # if $SRC was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR=$( cd -P "$( dirname "$SRC" )" >/dev/null 2>&1 && pwd )

$DIR/setup-odoo-repository odoo community true
$DIR/setup-odoo-repository enterprise
$DIR/setup-odoo-repository upgrade
$DIR/setup-odoo-repository upgrade-util
$DIR/setup-odoo-repository design-themes extra-addons/design-themes
$DIR/setup-odoo-repository industry extra-addons/industry
$DIR/setup-odoo-repository docker
$DIR/setup-odoo-repository documentation
$DIR/setup-odoo-repository o-spreadsheet
$DIR/setup-odoo-repository owl
$DIR/setup-odoo-repository paper-muncher
