#!/usr/bin/env bash

# Requires pre-commit command to be installed.
# See: https://pre-commit.com or try `pip install pre-commit`

# First, we need to get the directory of this script.
# See: https://stackoverflow.com/a/246128
SRC=${BASH_SOURCE[0]}
while [ -L "$SRC" ]; do # resolve $SRC until the file is no longer a symlink
    DIR=$( cd -P "$( dirname "$SRC" )" >/dev/null 2>&1 && pwd )
    SRC=$(readlink "$SRC")
    [[ $SRC != /* ]] && SRC=$DIR/$SRC # if $SRC was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR=$( cd -P "$( dirname "$SRC" )" >/dev/null 2>&1 && pwd )

pushd $DIR/.. > /dev/null

pre-commit install -t pre-commit -t commit-msg -t pre-push

popd > /dev/null
